name: Checks

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ master ]

jobs:
  wrapper-validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2

  ktlint:
    name: "ktlint"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "Install ktlint"
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.5.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: "Run ktlint"
        run: sh .ci/lint.sh ktlint

  codespell:
    name: "codespell"
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - name: "Install codespell"
        run: sudo apt install codespell -y
      - name: "Run codespell"
        run: sh .ci/lint.sh codespell
